### ISSUE TITLE
    from tensorflow.python.keras._impl.keras.layers import Lambda ImportError: No module named _impl.keras.layers

### ISSUE THREAD

**Issue by Outstandingwinner** [shenweichen/DeepMatch#1]
python run_dssm_negsampling.py 
Traceback (most recent call last):
  File "run_dssm_negsampling.py", line 7, in <module>
    from deepmatch.models import *
  File "/miniconda2/lib/python2.7/site-packages/deepmatch/__init__.py", line 1, in <module>
    from .utils import check_version
  File "/miniconda2/lib/python2.7/site-packages/deepmatch/utils.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras.layers import Lambda
ImportError: No module named _impl.keras.layers

**Comment by Outstandingwinner** [comment]
解决了，tensorflow1.14.0 版本不对，改为1.4.0成功执行

**Comment by wangzhegeek** [comment]
> 解决了，tensorflow1.14.0 版本不对，改为1.4.0成功执行

近期会做版本适配
