### ISSUE TITLE
run_youtubednn.py 出错

### ISSUE THREAD

**Issue by lixiao1234567** [shenweichen/DeepMatch#64]
Please refer to the [FAQ](https://deepmatch.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepMatch/issues) before you ask the question.

**Describe the question(问题描述)**
when executing run_youtubednn.py, I get error :

Traceback (most recent call last):
  File "/data/gitlab/test/DeepMatch/examples/run_youtubednn.py", line 62, in <module>
    model = YoutubeDNN(user_feature_columns, item_feature_columns, num_sampled=5, user_dnn_hidden_units=(64, embedding_dim))
  File "/data/gitlab/tes/DeepMatch/deepmatch/models/youtubednn.py", line 57, in YoutubeDNN
    dnn_use_bn, output_activation=output_activation, seed=seed)(user_dnn_input)
  File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 784, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 699, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.FailedPreconditionError: in user code:

    File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/deepctr/layers/core.py", line 193, in call  *
        fc = self.activation_layers[i](fc)
    File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/keras/engine/base_layer_v1.py", line 732, in __call__  **
        base_layer_utils.create_keras_history(inputs)
    File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/keras/engine/base_layer_utils.py", line 175, in create_keras_history
        _, created_layers = _create_keras_history_helper(tensors, set(), [])
    File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/keras/engine/base_layer_utils.py", line 251, in _create_keras_history_helper
        constants[i] = backend.function([], op_input)([])
    File "/data/tools/anacoda/anacoda-install/envs/tf-py3.7/lib/python3.7/site-packages/keras/backend.py", line 4187, in __call__
        run_metadata=self.run_metadata)

    FailedPreconditionError: Could not find variable dnn/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/dnn/bias0)
    	 [[{{node dnn/BiasAdd/ReadVariableOp}}]]

**Additional context**
no

**Operating environment(运行环境):**
 - python version 3.7 
 - tensorflow version 2.7.0 
 - deepmatch version 0.2.0

**Comment by Beytab** [comment]
tf 2.7不行，要用低版本

**Comment by lixiao1234567** [comment]
no error after change to tf1.13.2
